# Generated by Django 3.2.5 on 2021-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='MEDIA/'),
            preserve_default=False,
        ),
    ]
