# Generated by Django 3.2.5 on 2021-07-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_profile_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='live',
            new_name='live_link',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='repo_url',
        ),
    ]
